# Generated by Django 6.0.2 on 2026-04-08 10:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Einleitungstext für die Blog-Übersicht')),
            ],
            options={
                'verbose_name': 'Blog Übersicht',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('excerpt', models.CharField(help_text='Kurzbeschreibung für die Artikelliste', max_length=500)),
                ('content', models.TextField(help_text='Artikel-Inhalt (HTML)')),
                ('category', models.CharField(choices=[('Kaufberatung', 'Kaufberatung'), ('Spartipps', 'Spartipps'), ('Technik', 'Technik'), ('Nachrichten', 'Nachrichten'), ('Testberichte', 'Testberichte')], default='Kaufberatung', max_length=50)),
                ('amazon_keywords', models.CharField(blank=True, help_text='Kommagetrennte Amazon-Keywords', max_length=500)),
                ('amazon_product_url', models.URLField(blank=True, help_text='Amazon-Produkt-URL (falls vorhanden)', max_length=500)),
                ('product_names', models.CharField(blank=True, help_text='Produktnamen für Produktkarten (kommagetrennt, z.B. Sony WH-1000XM5, Bose QuietComfort 45)', max_length=500)),
                ('author', models.CharField(default='Sugesto Redaktion', max_length=100)),
                ('read_time', models.IntegerField(default=5, help_text='Lesezeit in Minuten')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, help_text='Titelbild (wird auf Cloudinary gespeichert)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog Artikel',
                'verbose_name_plural': 'Blog Artikel',
            },
            bases=('wagtailcore.page',),
        ),
    ]
